action_inherited();
scr_dialog("strad","Haha!            #That was great lil' dude!")
scr_dialog("strad","Y'know you didn't do#too bad keeping up!#Have you been practicing?")
scr_dialog("dude","nah! just pure tallent!")
scr_dialog("tv","THAT IS A FABRICATION")
scr_dialog("dude",">:(")
scr_dialog("strad","cool.")
scr_dialog("strad","Lets move onto the next song.")
scr_dialog("strad","Now this song is pretty#special to me.")
scr_dialog("strad","I remember singin' this back in#the karaoke championships of 99'") //karokate
scr_dialog("strad","I destroyed my competition#and had the choice#to go to the national#championship.")
scr_dialog("strad","And that was a big deal!            #It would have been aired#on national television!#seen by thousands of people!")
scr_dialog("strad","But then I met lady's#mother.")
scr_dialog("strad","She was amazing!#I've never met anyone like#her before")
scr_dialog("strad","And I knew that if I decided to go#pro, I would never be able#to see her again.")
scr_dialog("strad","So I decided to quit.            #the runner up ended up#taking my place in the#championship.")
scr_dialog("strad","I don't know where I would be#if I had decided to go pro.")
scr_dialog("strad","Who knows!            #Maybe I could have been#a star myself!")
scr_dialog("strad","But I doubt the life of a#star was for me anyway,#and I'm glad I made#the choice I did.")
scr_dialog("strad","I would never give up#the life I have now#for anything.")
scr_dialog("strad","But enough with that sappy#stuff...")
scr_dialog("strad","Lets rock lil' dude!")