action_inherited();
txt[1]="But uh, anyway. About your ^Pdad^W...#Does he actually know we're#dating?"
voice[1]="dude"
txt[2]="y"
voice[2]="lady"
txt[3]="Oh nuts."
voice[3]="dude"
txt[4]="i"
voice[4]="lady"
txt[5]="Well, you know how dads are#with people dating their#daughters!"
voice[5]="dude"
txt[6]="I mean...               #in cartoons.        #But those are real!"
voice[6]="dude"
txt[7]="Your dads gonna be PISSED#when he finds out we're#dating!"
voice[7]="dude"
txt[8]="Theres gotta be something I can#do to get on his good side..."
voice[8]="dude"
txt[9]="i"
voice[9]="lady"
txt[10]="Huh?    #What'cha looking at?"
voice[10]="dude"
txt[11]="Looks like a...     #Karaoke machine?"
voice[11]="dude"
txt[12]="wait...             #I think I got something!"
voice[12]="dude"
textmax=12

