action_inherited();
scr_dialog("buddy","And that'll be 8.50#Enjoy your time on the rink!")
scr_dialog("buddy","And hey!         #Maybe on your way out#you can check out the#arcade?")
scr_dialog("buddy","...")
scr_dialog("vinyl","I'd really hate to break#it to you,                         #But I dont think they caught#a word of that");
scr_dialog("vinyl","Honestly its beyond me why you#think people are going to#start caring about those old#crappy games again.")
scr_dialog("buddy","Oh I don't wanna hear you#calling those games crappy!")
scr_dialog("buddy","Like, have you even played#legend of the shadow walker?")
scr_dialog("vinyl","Yeah actually I played it#on my break and-")
scr_dialog("vinyl","No.")
scr_dialog("vinyl","No I have not.         #And nobody else has either.")
scr_dialog("vinyl","Besides maybe that one#chick that hangs around#here sometimes.")
scr_dialog("dude","✓♠BUDDYYYYYYYYYYYY!!!!")
scr_dialog("dude","✓♠BUDDY-BUDDY-BUDDY    #YOU'VE GOTTA HELP ME!")
scr_dialog("buddy","Is it about the job application#or Cd boy?")
scr_dialog("dude","cd boy!          #He's-")
scr_dialog("dude","wait what? how do you know#about that?")
scr_dialog("buddy","I have my ways...")
scr_dialog("vinyl","He saw the whole thing.           #'told me all about it.")
scr_dialog("vinyl","Says you crushed#him with a karaoke machine#on the bus?")
scr_dialog("buddy","Aw come on!                #Not cool!")
randomize();
//this was funne's idea
var nutman=round(random(14000000000))
if nutman=10 {
    scr_dialog("dude","aw nut man sorry!       #is that how you got the cast?")
} else {
    scr_dialog("dude","aw nuts man sorry!       #is that how you got the cast?")
}
scr_dialog("buddy","Oh no way.                 #While working here like 30#arcade machines have#fallen on me.")
scr_dialog("buddy","I've got like a resilience to#stuff like that by now")
scr_dialog("dude","so where did you get it from?")
scr_dialog("buddy","...")
scr_dialog("buddy","nowhere")
scr_dialog("vinyl","great.")
scr_dialog("buddy","But yeah,         #I can probably fix this#guy up.")
scr_dialog("dude","sweet!")
scr_dialog("dude","so do you have a toolbox#somewhere or...")
scr_dialog("buddy","Aw come on little J,       #I'm a professional!")
scr_dialog("buddy","I don't do my work behind#the counter at an arcade")
scr_dialog("buddy","A true master-mechanic like#me has to have a workshop!")
scr_dialog("buddy","Let me show you.")
scr_dialog("buddy","Hey vinyl,           #I'm going on break.")
scr_dialog("buddy","You're gonna have to hold#things over for like...                     #anywhere between...           #3 minutes to 3 hours.")
scr_dialog("vinyl","I hate you.")
scr_dialog("buddy","Alright,               #heres my workshop.")
scr_dialog("dude","uh buddy...           #thats a wall")
scr_dialog("buddy","Guess I should have been#more specific.")
scr_dialog("buddy","This is the entrance.")
scr_dialog("buddy","All you gotta do is#push up against this wall and...")
scr_dialog("buddy","✓㋡tada~")
scr_dialog("dude","WOAAAAAH")
scr_dialog("dude","man this is so RAD how#did you even find this place!!!")
scr_dialog("buddy","Found it while I was on#cleaning duty.")
scr_dialog("buddy","No idea why its here or#what it's meant for.")
scr_dialog("buddy","But I spend most of my breaks here.#where I do my freelance work#as a mechanic.")
scr_dialog("buddy","And I'd say its the perfect#place for someone whos planning#to take over the world.")
scr_dialog("dude","you want to take over the#world?")
scr_dialog("buddy","Yeah man taking over the world#would be awesome.")
scr_dialog("buddy","Finally getting out of#this dead end job and#getting to be the one in#charge")
scr_dialog("dude","just make sure to#give me a cool job ok?")
scr_dialog("buddy","Yeah, you could be like.          #^YThe royal toilet scrubber.")
scr_dialog("dude","eeeeeew!!!           #But I guess it's better than#what I have now.")
scr_dialog("dude","...")
scr_dialog("buddy","Well this is probably going to#take me awhile.")
scr_dialog("buddy","I've got some spare change#If you wanna go out and#play some of the arcade games")
scr_dialog("dude","oh no its fine!                       #I found a dollar on the ground#on my way over here!")
scr_dialog("tv","")
scr_dialog("dude","huh?")
scr_dialog("buddy","Oh don't mind that,           #It's been doing that since#I brought it back here")
scr_dialog("dude","you brought it here?")
scr_dialog("buddy","I couldn't just leave it on#the bus!")
scr_dialog("buddy","But it doesn't seem to be#working anyway.")
scr_dialog("buddy","It keeps saying it's missing#files.                #The software for that old thing#is so outdated I might just use#it for parts.")
scr_dialog("dude","but what about Teachvee!          #You'll kill him!")
scr_dialog("buddy","who?")
scr_dialog("dude","the little man in the computer!")
scr_dialog("dude","he's the reason I was#able to stand up to Strad!")
scr_dialog("dude","and he even stopped me from#getting my head handed#to me by Cyan!")
scr_dialog("dude","he's just a little guy!               #he's just like me!")
scr_dialog("dude","us little guys have to stick#together!                #We gotta help him!")
scr_dialog("buddy","I guess I can put aside him#crushing my seat on the bus if he#really did all of that.")
scr_dialog("dude","yeah!")
scr_dialog("dude","I got my microphone still!          #I'm sure we can sing this guy#back to life!")
scr_dialog("buddy","I'm not sure if thats how that#works but we can give that a shot.")
scr_dialog("buddy","I even got a microphone too.")
scr_dialog("buddy","I'm not too great at singing#so I hope you don't mind if we#sing an easy song.")
scr_dialog("buddy","Does Twinkle sound good?")
scr_dialog("dude","heckles yeah!")
scr_dialog("buddy","Sweet.")