action_inherited();
txt[1]="Hey kiddos what'cha doing?"
voice[1]="strad"
txt[2]="Uh! Nothing! Actually I was just#heading out and--"
voice[2]="dude"
txt[3]="Oh hey!#You guys dug out the#old karaoke machine!"
voice[3]="strad"
txt[4]="Say, why dont we bring that old#thing out back and have a#few rounds?"
voice[4]="strad"
txt[5]="Y'know in my day they used to#call me the 'karaoke king'"
voice[5]="strad"
txt[6]="Uh....."
voice[6]="dude"
txt[7]="Sure? I'm down...."
voice[7]="dude"
txt[8]="Alright!         #Say ill meet ya out back#and we'll sing one of my#favorites!"
voice[8]="strad"
txt[9]="Okay!..."
voice[9]="dude"
txt[10]="..."
voice[10]="dude"
txt[11]="I'm so dead..."
voice[11]="dude"
textmax=11

