action_inherited();
scr_dialog("strad","Hey kiddos what'cha doing?")
scr_dialog("dude","uh! nothing! actually I was just#heading out and--")
scr_dialog("strad","Oh hey!#You guys dug out the#old karaoke machine!")
scr_dialog("strad","Say, why dont we bring that old#thing out back and have a#few rounds?")
scr_dialog("strad","Y'know in my day they used to#call me the 'karaoke king'")
scr_dialog("dude","uh.....")
scr_dialog("dude","sure? I'm down....")
scr_dialog("strad","Alright!         #Say ill meet ya out back#and we'll sing one of my#favorites!")
scr_dialog("dude","okay!...")
scr_dialog("dude","...")
scr_dialog("dude","I'm so dead...")