action_inherited();
scr_dialog("strad","Man that was great!#")
scr_dialog("dude","holy crap!         #how did you learn to#sing like that!")
scr_dialog("strad","That little karaoke machine#is a great mentor")
scr_dialog("tv","YOU WERE ALWAYS MY FAVORITE#STUDENT")
scr_dialog("strad","I dont remember it being#able to make conversation#though.")
scr_dialog("dude","yeah,             #uh Strad sir I have#a question")
scr_dialog("strad","Yeah what is it sport?")
scr_dialog("dude","i was uh y'know wondering if like..#well y'know if i uh,#y'know uh.....#y'know...")
scr_dialog("strad","No I really don't know")
scr_dialog("dude","I WAS WONDERING IF I COULD#GO OUT WITH YOUR DAUGHTER")
scr_dialog("dude","...")
scr_dialog("lady","s")
scr_dialog("strad","...")
scr_dialog("strad","I thought you already were.")
scr_dialog("dude","...")
scr_dialog("dude","I HATE MY LIFE")
scr_dialog("lady","w")
scr_dialog("strad","Well I have no idea what that was.")
scr_dialog("strad","But you probably should#be gettin' home.")
scr_dialog("strad","It's the first day of school #tomorrow and you wouldn't want to#be tired on the first day!")
scr_dialog("dude","d'aw what?")
