action_inherited();
txt[1]="FRIENDS, FRIENDS!#IS SUCH VIOLENCE REALLY#NECESSARY?"
voice[1]="tv"
txt[2]="???"
voice[2]="cyan"
txt[3]="THINK ABOUT IT ^B[CYAN]^W--"
voice[3]="tv"
txt[4]="how do you know my name."
voice[4]="cyan"
txt[5]="WOULDN'T IT BE MUCH MORE#SATISFYING TO BEAT THIS FIEND#AT HIS OWN GAME?"
voice[5]="tv"
txt[6]="hey whos side are you on!"
voice[6]="dude"
txt[7]="clearly not yours LOL!"
voice[7]="cyan"
txt[8]="did you just say 'lol'#out loud?"
voice[8]="dude"
txt[9]="wait shut the %$!& up idc#hey do you have girl#next door by ^SGUNK!^W"
voice[9]="cyan"
txt[10]="I HAVE A VERY#WIDE SELECTION OF SONGS#BY THE ARTIST ^SGUNK^W"
voice[10]="tv"
txt[11]="oh you are getting REKT KID!"
voice[11]="cyan"
txt[12]="if you lose this one#say goodbye to your#legs!!!"
voice[12]="cyan"
txt[13]="c-cool"
voice[13]="dude"
txt[14]="r"
voice[14]="lady"
textmax=14

//lol
randomize();
nermal=round(random(100))


/*
txt[1]="what the!"
voice[1]="dude"
txt[2]="???"
voice[2]="cyan"
txt[3]="say..."
voice[3]="cyan"
txt[4]="actually,"
voice[4]="cyan"
txt[5]="this gives me an idea."
voice[5]="cyan"
txt[6]="maybe I dont have to do#anything physical to get#my point across."
voice[6]="cyan"
txt[7]="maybe if I beat you at your#own STUPID game, you'll die#of shame!"
voice[7]="cyan"
txt[8]="can you actually die of#shame?"
voice[8]="dude"
txt[9]="a"
voice[9]="lady"
txt[10]="but hey! if you can beat#me in a song of my choosing!"
voice[10]="cyan"
txt[11]="then just MAYBE#ill let you have my seat!"
voice[11]="cyan"
txt[12]="and if I dont?"
voice[12]="dude"
txt[13]="wheelchair."
voice[13]="cyan"
txt[14]="oh...                  #c-cool."
voice[14]="dude"
txt[15]="well uh.....        #what song....            #do you wanna play?????"
voice[15]="dude"
txt[16]="girl next door by ^SGUNK!"
voice[16]="cyan"
txt[17]="great, im gonna die#while listening to crappy pop#music"
voice[17]="dude"
txt[18]="lady... if I dont make#it out alive just know I love you                 #and my ability to walk..."
voice[18]="dude"
textmax=18

/* */
/*  */
