action_inherited();
scr_dialog("cyan","OH I TOTALLY BEAT YOU!!!")
scr_dialog("cyan","Right TV boy!")
scr_dialog("tv","INCORRECT.")
scr_dialog("tv",string("^Y[DUDE]^W WON WITH ")+string(obj_stats.gndscore)+string(" POINTS"))
scr_dialog("tv","YOU LOST WITH...                    #0 POINTS")
scr_dialog("cyan","WTFFFFFFFF#I LOST????               #HOW? I SING THAT#SONG LIKE EVERYDAY!!!")
scr_dialog("dude","yeah uh...         #I won right???           #that means uh...           #you're not gonna tear my legs off?")
scr_dialog("cyan","UUUUUUUGH whatevs...       #tbh I probably wasn't going#to do that anyway")
scr_dialog("dude","then what were the scary#threats for!!!")
scr_dialog("cyan","come oooooooooooooon man,#I was JOKING")
scr_dialog("dude","joking?!?!?!                #that joke sucked!               #like, how was I supposed#to know you're joking!")
scr_dialog("lady","r")
scr_dialog("dude","oh come on! the one with#the dog is different#and you know that!")
scr_dialog("cyan","ugh... WHATEVER, look you won my#seat. ill go sit up front or#something")
scr_dialog("cyan","good luck trying to find#a seat for your girl#tho lolololololol")
scr_dialog("dude","yeah thanks.")
scr_dialog("dude","wait, why would I have#trouble finding a seat for you#lady?")
scr_dialog("cd","//because cyan was not sitting#//alone                    #//so only one seat is open")
scr_dialog("dude","wha-         #who even are you!")
scr_dialog("cd","//my name is cd-boy       #//my purpose given to me by my#//creator cyan is to--")
scr_dialog("cd","^Ascr_voice^Q(^Z'cyan'^Q);^W#//'play video games with me!'#//'and eat disks!'")
scr_dialog("cd","^Ascr_audioplay^Q(^Zsnd_win^Q);^W")
scr_dialog("dude","well uh,         #hi?               #do you think we can have#your seat?")
scr_dialog("cd","//no.              #//but, you can earn it")
scr_dialog("cd","//I saw you and my creator#//cyan lyrically duking it out.                  #//I want a piece of that action")
scr_dialog("tv","YOUR PARTICIPATION WOULD BE#GREATLY APPRECIATED")
scr_dialog("cd","//I do not believe I#//requested your input old man.#^Ascr_audioplay^Q(^Zsnd_own^Q);^W")
scr_dialog("tv","\\/")
scr_dialog("cd","//the rules are simple.           #^Qyou_win = ^Z'you get my seat'#^Qi_win = ^Z'you both buzz off'")
scr_dialog("dude","if it gives me a#seat then you've got yourself#a battle!")
scr_dialog("cd","//unfortunately winning will not#//get you a step stool so you#//can reach the top shelf#^Ascr_audioplay^Q(^Zsnd_own^Q);^W")
scr_dialog("dude",">:(")
scr_dialog("lady","h")
scr_dialog("lady","j")
scr_dialog("lady","o")
scr_dialog("lady","k")
scr_dialog("dude","woah! hey!#lady!")
scr_dialog("dude","...            #huh?...                        #hahaha!")
scr_dialog("dude","whos the short one now#crap-dumb boy!")
scr_dialog("lady","l")
scr_dialog("cd","/*...         #            #            #          #*/")
scr_dialog("cd","//connection established with#//'S's karaoke machine'")
scr_dialog("cd","^Avar ^Qsong = ^Z'GameBoy'^Q;#^Avar ^Qdifficulty = ^Z'EXTREME'^Q;#^Ascr_songboot^Q(song,difficulty);^W")
scr_dialog("dude","aw nuts.")

/* */
///variables
sound=false

/* */
/*  */