action_inherited();
scr_dialog("cd","___________________#@@@@@@@@@@@@@@@@@@@#FATAL ERROR in#action number 999#of Step Event999#for object obj_cdboy:")//##Unable to find any instance for object index '999' name 'misplaced'# at cdl_script_scr_songboot (line 999) -         song=misplaced#@@@@@@@@@@@@@@@@@@@#___________________#stack frame is#cdl_Script_scr_songboot (line 999)")
scr_dialog("cd","//ERROR ERROR//")
scr_dialog("cd","INTERNAL TEMPATURE: TOO HIGH              #FIREWALL: IN BITS              #GAME: JACKED")
scr_dialog("dude","y'know im not a rocket surgeon#but I dont think he's supposed#to be doing that")
scr_dialog("lady","s")
scr_dialog("dude","hey teachvee do you#have any idea whats#going on?")
scr_dialog("dude","...")
scr_dialog("dude","y'know,            #because                   #y-you're a computer?")
scr_dialog("lady","j")
scr_dialog("dude","I guess he's taking#a bathroom break or#something")
scr_dialog("cyan","ok cd, were here     #lets go--")
scr_dialog("dude","...")
scr_dialog("lady","e")
scr_dialog("cyan","...                               #MY ROBOT!!!!                   #✓♠DUUDE IM GONNA KILL YOU!!!✓W")
scr_dialog("dude","haha! I get that joke!")
scr_dialog("cyan","/SRS")
scr_dialog("dude","OH NUTS")
scr_dialog("cyan","✓♠HSDFHJFKLASJDFHJSKDHF✓W")
scr_dialog("cd","✓♠ERRORERRORERRORERROR✓W")
scr_dialog("dude","h-hey!               #I-I-I can fix him!")
scr_dialog("cyan","✓♠EWR✓W- huh?")
scr_dialog("dude","y-yeah!        #I um,               #I know a guy!")
scr_dialog("cyan","you know a guy??")
scr_dialog("dude","yeah he's a genius!")
scr_dialog("dude","like, one time I asked#him to solve a multiplication#problem with ^R✓㋡THREE DIGIT NUMBERS!^W✓W")
scr_dialog("cyan","...                                  #did he solve it.")
scr_dialog("dude","yeah!                #so I bet he can fix up#cd boy!")
scr_dialog("cyan","...                 #ooookay")
scr_dialog("cyan","but just you know if#you dont have cd boy all#fixed up by ^R5:30 tomarrow^W#you're gonna be seeing stars!")
scr_dialog("lady","i")
scr_dialog("dude","why 5:30")
scr_dialog("cyan","An update to our FAVORITE game#is releasing tomorrow!#theres no way were going to#miss it!")
scr_dialog("dude","o-of course")
scr_dialog("cyan","see you then you little TROLLS.")
scr_dialog("lady","r")
scr_dialog("dude","I guess I didn't have#anything cool going on#tomorrow anyway.")

