action_inherited();
scr_dialog("dude","man it's FREEZING out here!")
scr_dialog("dude","I can't even feel my#arms right now!")
scr_dialog("lady","i")
scr_dialog("dude","do I want your coat?")
scr_dialog("dude","oh no lady its fine!                      #just because I couldn't #fork up the cash to get a coat#doesn't mean you should be cold!")
scr_dialog("dude","and im sure that the bus#is going to be here any#second now!")
scr_dialog("lady","e")
scr_dialog("dude","its fine!       #dont worry about it!!")
scr_dialog("lady","h")
scr_dialog("dude","see!             #the bus is already here!")
scr_dialog("dude","ok lady so heres the thing,                     #everyone says the cool kids#sit in the seats in the#back right?")
scr_dialog("lady","u")
scr_dialog("dude","well they're WRONG!")
scr_dialog("lady","p")
scr_dialog("dude","the REAL cool kids sit#in the seat next to#^Remergency exit!^W")
scr_dialog("dude","think about it!            #if this hunk of metal gets#in a wreck, whos getting out#first?")
scr_dialog("lady","e")
scr_dialog("dude","huh whats up?            #oh,")
scr_dialog("dude","oh, looks like someone#beat us to it")
scr_dialog("dude","uh hey man,                  #is it cool if we sit here?")
scr_dialog("cyan","ugh, what                   #oh sorry, I didn't get too#much sleep last night.")
scr_dialog("cyan","some butthead with a lame blue hat#and a dorky pink turtleneck kept#me up all night with his#singing...")
scr_dialog("cyan","Can you believe that?")
scr_dialog("dude","oh really?          #sounds like a jerk!")
scr_dialog("cyan","YEAH! if I ever get my#hands on him ill uh...")
scr_dialog("cyan","wait....")
scr_dialog("cyan","lame blue hat...")
scr_dialog("cyan","dorky pink turtleneck...")
scr_dialog("cyan","✓♠WAIT A MINUTE YOU'RE THAT#BUTTHEAD!!!✓W")
scr_dialog("dude","what!?!          #that cant be true!          #I'm not known for my butt-like#complexion!")
scr_dialog("cyan","???")
scr_dialog("cyan","ugh.")
scr_dialog("cyan","man, I couldn't sleep at all#because of that trash#you were singing last night!")
scr_dialog("dude","listen tall girl, im sorry#we kept you up all night!#but could we please just have#your seat?")
scr_dialog("cyan","oh you want a seat?             #oh i'll give you one!")
scr_dialog("dude","oh sweet really?")
scr_dialog("cyan","yeah!              #in the wheelchair you'll be in#after I rip your legs off!")
scr_dialog("lady","f")
scr_dialog("dude","UH, Y'KNOW ILL THINK ILL#PASS ACTUALLY")
scr_dialog("tv","FRIENDS, FRIENDS!#IS SUCH VIOLENCE REALLY#NECESSARY?")
scr_dialog("cyan","???")
scr_dialog("tv","THINK ABOUT IT ^B[CYAN]^W--")
scr_dialog("cyan","how do you know my name.")
scr_dialog("tv","WOULDN'T IT BE MUCH MORE#SATISFYING TO BEAT THIS FIEND#AT HIS OWN GAME?")
scr_dialog("dude","hey whos side are you on!")
scr_dialog("cyan","clearly not yours LOL!")
scr_dialog("dude","did you just say 'lol'#out loud?")
scr_dialog("cyan","wait shut the %$!& up idc#hey do you have girl#next door by ^SGUNK!^W")
scr_dialog("tv","I HAVE A VERY#WIDE SELECTION OF SONGS#BY THE ARTIST ^SGUNK^W")
scr_dialog("cyan","oh you are getting REKT KID!")
scr_dialog("cyan","if you lose this one#say goodbye to your#legs!!!")
scr_dialog("dude","c-cool")
scr_dialog("lady","r")

///variables
randomize();
nermal=round(random(100))
whamcity=false
whamcityc=0
//songIndex = 0;
//audioBusNormal = audio_bus_main.effects[0]