action_inherited();
scr_dialog("CDEE","✓♠BRAVO! BRAVO!")
scr_dialog("cd","✓♠CRITICAL ERROR")
scr_dialog("CD-BOY","✓♠NO")
scr_dialog("CD-BOY","✓♠LISTEN-TO-ME")
scr_dialog("CD-BOY","✓♠I-DON'T-WANT-YOU#TO-BE-HERE")
scr_dialog("CD-BOY","✓♠DUDE")
scr_dialog("CD-BOY","✓♠I-CAN-SEE-IT")
scr_dialog("buddy","shut up!")
scr_dialog("peeb","...")
scr_dialog("peeb","...")
scr_dialog("cd","//hello world")
scr_dialog("dude","oh shoot he's up!")
scr_dialog("dude","a-are you going to kill me?")
scr_dialog("cd","//probably at some point.")
scr_dialog("dude","oh hey he's normal again")
scr_dialog("buddy","Yeah that sounds#about right.")
scr_dialog("buddy","That anti-virus just#finished installing")
scr_dialog("buddy","It didn't find anything#though.")
scr_dialog("buddy","Where did--")
scr_dialog("tv","CONGRATULATIONS ^Y[DUDE]^W!")
scr_dialog("tv","YOU BEAT THE BADGUY#AND WON THE PRIZE!")
scr_dialog("tv","ALL BY YOURSELF.")
scr_dialog("buddy","*clears throat*")
scr_dialog("tv","YOURSELVES")
scr_dialog("dude","where were you TeachVee!       #we could have used#your help with that virus!")
scr_dialog("tv","I HELPED")
scr_dialog("dude","what?")
scr_dialog("cd","//I really doubt it")
scr_dialog("cd","//wait a cycle")
scr_dialog("cd","//my internal clock is offline                  #//what time is it?")
scr_dialog("buddy","uhh...          #5:32")
scr_dialog("dude","...")
scr_dialog("dude","!!!")
scr_dialog("dude","✓♠AAAAAAAAAAAAAAAAAAAAA✓W#CYAN IS GOING TO KILL ME")
scr_dialog("dude","OK CD BOY ITS TIME TO#GO")
scr_dialog("cd","^Ascr_setTime^Q(^Z'to go'^Q);")
scr_dialog("dude","C'MON C'MON C'MON!")
scr_dialog("buddy","Hey wait! You forgot your#free t-shirt!")
scr_dialog("buddy","...")
scr_dialog("buddy","No one ever wants the t-shirt.")
scr_dialog("dude","C'MON C'MON C'MON!")
scr_dialog("dude","✓♠OUGH!!!")
scr_dialog("dude","oh jeez! sorry man!          #I didn't see you there!")
scr_dialog("gunk?","...")
scr_dialog("dude","uh...                      #whats that look for")
scr_dialog("gunk?","oookay you got me")
scr_dialog("dude","what?")
scr_dialog("gunk?","bro you got me#you dont have to#play dumb anymore.")
scr_dialog("dude","uuuh, cd-boy?")
scr_dialog("cd","//...")
scr_dialog("cd","//my facial recognition#//software is offline.")
scr_dialog("cd","//I don't know#//who you are miss")
scr_dialog("gunk?","Yeah right, cut the crap!")
scr_dialog("peeb","...")
scr_dialog("gunk","You know I'm gunk!")
scr_dialog("cd","^Ascr_playsound^Q(^Zsnd_gasp^Q);")
scr_dialog("dude","wait! like the popstar!?")
scr_dialog("gunk","uh... yeah???")
scr_dialog("gunk","Wait did you two seriously#not know?")
scr_dialog("cd","//its almost as if we#//were telling you that#//the whole time.")
scr_dialog("cd","//good job blowing your cover.")
scr_dialog("cd","//maybe next time someone else#//can see through your disguise")
scr_dialog("gunk","✓♠uuuuuuuuuugh")
scr_dialog("gunk","Man you guys can't let#anyone know I hang out here.")
scr_dialog("dude","is it that embarrassing for people#know that you play video games?")
scr_dialog("gunk","No, not               #not that.")
scr_dialog("gunk","This is the only place#where people don't know#I'm some celebrity")
scr_dialog("gunk","I can't go anywhere without#getting swarmed by people.")
scr_dialog("gunk","Just keep your#mouth shut okay.")
scr_dialog("cd","//what would we get#//out of it")
scr_dialog("gunk","ugh, you want an autograph#or something?")
scr_dialog("dude","I WANT A BILLION DOLLARS--")
scr_dialog("cd","//give us 4 ultra super deluxe#//tickets to your next show")
scr_dialog("gunk","Yeah-yeah alright sure here.")
scr_dialog("gunk","Now scram!")
scr_dialog("dude","yeah ok,     #im late to having my legs#ripped off anyway")
scr_dialog("gunk","What?")
scr_dialog("dude","so youre a fan of gunk?")
scr_dialog("cd","//yes, my creator designed me#//in every way to be just like#//her")
scr_dialog("cd","//so I could be her#//perfect player 2")
scr_dialog("cd","//but lately cyan has been#//acting rather unoptimized#//after she wasn't able to get#//tickets to gunk's latest concert")
scr_dialog("cd","//im sure when you show her these#//she'll forget all about you#//being late")
scr_dialog("cd","//consider#^Qmy_debt_to_you=^Z'repaid'")
scr_dialog("dude","aw sweet thanks man!")
scr_dialog("cd","//these remainder tickets are#//for you and your buddy                #^Qmy_debt_to_you=^Z'over-paid'")
scr_dialog("dude","i dunno, me and buddy both#hate her music")
scr_dialog("cd","//its ok to have a bad taste#//in music")
scr_dialog("dude","but im sure lady would love to go!")
scr_dialog("dude","so like, whats so special#about these tickets anyway?")
scr_dialog("dude","what makes them                    #✓㋡'super ultra deluxe'")
scr_dialog("cd","//these tickets allow you#//to go on-stage and sing with#//gunk herself")
scr_dialog("dude","...")
scr_dialog("peeb","SPOOKY SHIT GOES HERE MAN!")

///variables
blinking=0
sound=false

